"""
constants.py

Daftar nilai unik Make/Type/Region dkk, diambil langsung dari
UsedCarsSA_Clean_EN.csv (data training) untuk populate dropdown
di streamlit_app.py.
"""

GENERIC_TYPE_FALLBACK = "Lainnya / Tidak ada di daftar"

MAKE_OPTS = [
    'Aston Martin',
    'Audi',
    'BMW',
    'BYD',
    'Bentley',
    'Cadillac',
    'Changan',
    'Chery',
    'Chevrolet',
    'Chrysler',
    'Classic',
    'Daihatsu',
    'Dodge',
    'FAW',
    'Ferrari',
    'Fiat',
    'Ford',
    'Foton',
    'GAC',
    'GMC',
    'Geely',
    'Genesis',
    'Great Wall',
    'HAVAL',
    'Honda',
    'Hummer',
    'Hyundai',
    'INFINITI',
    'Isuzu',
    'Iveco',
    'Jaguar',
    'Jeep',
    'Kia',
    'Land Rover',
    'Lexus',
    'Lifan',
    'Lincoln',
    'MG',
    'MINI',
    'Maserati',
    'Mazda',
    'Mercedes',
    'Mercury',
    'Mitsubishi',
    'Nissan',
    'Other',
    'Peugeot',
    'Porsche',
    'Renault',
    'Rolls-Royce',
    'SsangYong',
    'Subaru',
    'Suzuki',
    'Tata',
    'Toyota',
    'Victory Auto',
    'Volkswagen',
    'Zhengzhou',
    'Škoda',
]

ORIGIN_OPTS = [
    'Gulf Arabic',
    'Other',
    'Saudi',
    'Unknown',
]

COLOR_OPTS = [
    'Another Color',
    'Black',
    'Blue',
    'Bronze',
    'Brown',
    'Golden',
    'Green',
    'Grey',
    'Navy',
    'Oily',
    'Orange',
    'Red',
    'Silver',
    'White',
    'Yellow',
]

OPTIONS_OPTS = [
    'Full',
    'Semi Full',
    'Standard',
]

FUEL_TYPE_OPTS = [
    'Diesel',
    'Gas',
    'Hybrid',
]

GEAR_TYPE_OPTS = [
    'Automatic',
    'Manual',
]

REGION_OPTS = [
    'Abha',
    'Al-Ahsa',
    'Al-Baha',
    'Al-Jouf',
    'Al-Medina',
    'Al-Namas',
    'Arar',
    'Aseer',
    'Besha',
    'Dammam',
    'Hafar Al-Batin',
    'Hail',
    'Jazan',
    'Jeddah',
    'Jubail',
    'Khobar',
    'Makkah',
    'Najran',
    'Qassim',
    'Qurayyat',
    'Riyadh',
    'Sabya',
    'Sakaka',
    'Tabouk',
    'Taef',
    'Wadi Dawasir',
    'Yanbu',
]

# Type per Make, diurutkan dari yang paling sering muncul di data training
MAKE_TYPE_MAP = {
    'Aston Martin': ['Vanquish', 'Vantage', 'DB9'],
    'Audi': ['A8', 'A6', 'Q5', 'A3', 'A4', 'A7', 'A5', 'S5', 'S8', 'Q7'],
    'BMW': ['The 7', 'X', 'The 5', 'The 3', 'The 4', 'The 6', 'The M', 'Z'],
    'BYD': ['F3', 'S7', 'S6'],
    'Bentley': ['Flying Spur', 'Arnage', 'Bentayga'],
    'Cadillac': ['Escalade', 'CT-S', 'CT6', 'XT5', 'ATS', 'CT5', 'CT4', 'Fleetwood', 'DTS', 'SRX', 'Other'],
    'Changan': ['Seven', 'Eado', 'CS95', 'CS75', 'CS35', 'V7', 'CS35 Plus', 'CS85'],
    'Chery': ['Tiggo', 'QQ'],
    'Chevrolet': ['Tahoe', 'Caprice', 'Suburban', 'Impala', 'Malibu', 'Silverado', 'Traverse', 'Camaro', 'Cruze', 'Aveo', 'Optra', 'Blazer', 'Spark', 'Lumina', 'Kaptiva', 'Abeka', 'Colorado', 'Trailblazer', 'Avalanche', 'Pick up'],
    'Chrysler': ['C300', '300', 'S300', 'C200', 'SRT', 'M300', 'New Yorker'],
    'Classic': ['Cadillac', 'Mini Cooper'],
    'Daihatsu': ['Delta', 'Gran Max', 'Terios', 'Terios Ground'],
    'Dodge': ['Charger', 'Durango', 'Challenger', 'Ram', 'Nitro', 'Dakota'],
    'FAW': ['B50', 'T77', 'X40', 'ِACTIS V80'],
    'Ferrari': ['GTB 599 Fiorano'],
    'Fiat': ['500', 'Doblo'],
    'Ford': ['Taurus', 'Expedition', 'Explorer', 'Marquis', 'Victoria', 'Edge', 'Mustang', 'Flex', 'Fusion', 'F150', 'Ranger', 'Echo Sport', 'Focus', 'Vego', 'Other', 'Van', 'Bronco', 'Transit', 'Thunderbird', 'Freestar'],
    'Foton': ['Mini Van', 'Suvana'],
    'GAC': ['GS3', 'GS8'],
    'GMC': ['Yukon', 'Sierra', 'Suburban', 'Acadia', 'Terrain', 'Envoy', 'Behbehani', 'Safari', 'Savana', 'C5700'],
    'Geely': ['EC7', 'Emgrand', 'X7', 'Azkarra', 'EC8', 'GS', 'Coolray', 'Other', 'GC7'],
    'Genesis': ['G80', 'Prestige', 'Royal', 'Platinum', 'G70', 'Prestige Plus', 'Other', 'Coupe', 'G330'],
    'Great Wall': ['Wingle', 'Power'],
    'HAVAL': ['H6', 'H2', 'H9'],
    'Honda': ['Accord', 'Odyssey', 'Civic', 'CRV', 'City', 'Other', 'Pilot', 'HRV', 'Crosstour'],
    'Hummer': ['H3', 'H-2'],
    'Hyundai': ['Accent', 'Sonata', 'Elantra', 'Senta fe', 'Azera', 'H1', 'Tucson', 'Kona', 'Creta', 'Genesis', 'Veloster', 'Bus County', 'Other', 'Coupe', 'Tuscani', 'Centennial', 'Coupe S', 'Avante', 'H100', 'i40', 'Veracruz'],
    'INFINITI': ['QX', 'Q', 'FX', 'G', 'M'],
    'Isuzu': ['D-MAX', 'Dyna', 'Other'],
    'Iveco': ['Daily'],
    'Jaguar': ['XF', 'XJ', 'F-Pace', 'F Type'],
    'Jeep': ['Grand Cherokee', 'Wrangler', 'Cherokee', 'Compass', 'Liberty', 'Patriot', 'Commander'],
    'Kia': ['Optima', 'Rio', 'Cerato', 'Cadenza', 'Sportage', 'Carnival', 'Sorento', 'Picanto', 'Mohave', 'Carenz', 'K5', 'Cores', 'Soul', 'Seltos', 'Opirus', 'Stinger', 'Carens', 'Sedona', 'Pegas'],
    'Land Rover': ['Range Rover', 'Defender', 'Discovery'],
    'Lexus': ['ES', 'LX', 'LS', 'RX', 'IS', 'GS', 'NX', 'GX', 'UX', 'RC'],
    'Lifan': ['LF X60'],
    'Lincoln': ['Navigator', 'MKX', 'Town Car', 'MKZ', 'MKS', 'Continental GT'],
    'MG': ['RX5', '5', 'ZS', '6', 'RX8', '360', 'GS', '3', 'T60', 'HS'],
    'MINI': ['Copper', 'Countryman'],
    'Maserati': ['Gamble', 'Quattroporte', 'Levante'],
    'Mazda': ['6', 'CX9', '3', 'CX5', 'CX3', '2', 'BT-50', 'CX7'],
    'Mercedes': ['S', 'C', 'E', 'CLA', 'ML', 'G', 'SEL', 'GLC', 'A', 'CLS', 'GL', 'GLE', 'POS24', 'SL', 'CL', 'Viano', 'SLK', 'Maybach', 'Actros'],
    'Mercury': ['Grand Marquis', 'Montero2', 'Milan'],
    'Mitsubishi': ['Pajero', 'Attrage', 'L200', 'Lancer', 'Outlander', 'Montero', 'Nativa', 'ASX', 'Other', 'L300', 'Galant'],
    'Nissan': ['Patrol', 'Sunny', 'Datsun', 'Altima', 'Pathfinder', 'Sentra', 'Navara', 'VTC', 'Maxima', 'X-Trail', 'Armada', 'Land Cruiser Pickup', 'KICKS', 'Bus Urvan', 'Sylvian Bus', 'Z370', 'X-Terra', 'Juke', 'Gloria', 'Murano', 'Z350', 'Silvia'],
    'Other': ['Other'],
    'Peugeot': ['301', '3008', 'Boxer', '5008', 'Partner', '307'],
    'Porsche': ['Cayenne', 'Panamera', 'Cayenne S', 'Macan', '911', 'Cayman', 'Cayenne Turbo S', 'Other', 'Cayenne Turbo', 'Cayenne Turbo GTS'],
    'Renault': ['Fluence', 'Dokker', 'Duster', 'Symbol', 'Capture', 'Safrane', 'Talisman', 'Koleos', 'Logan', 'Megane'],
    'Rolls-Royce': ['Ghost', 'Camargue'],
    'SsangYong': ['Koranado'],
    'Subaru': ['Forester'],
    'Suzuki': ['APV', 'Other', 'Jimny', 'Grand Vitara', 'Vitara', "D'max", 'Ertiga', 'Dzire', 'SX4'],
    'Tata': ['Nexon', 'Dyna'],
    'Toyota': ['Land Cruiser', 'Camry', 'Hilux', 'Corolla', 'Furniture', 'Prado', 'Yaris', 'FJ', 'Land Cruiser Pickup', 'Innova', 'Avalon', 'Rav4', 'Hiace', 'Land Cruiser 70', 'Ciocca', 'Cressida', 'Previa', 'Rush', 'Avanza', 'Aurion', 'Echo', '4Runner', 'Other', 'Corolla Cross', 'Dyna', 'C-HR', 'Coaster', 'Prius', 'Crown'],
    'Victory Auto': ['Van R'],
    'Volkswagen': ['Passat', 'Touareg', 'Tiguan', 'Beetle', 'CC', 'Jetta', 'Golf', 'Bora'],
    'Zhengzhou': ['Pick up'],
    'Škoda': ['Fabia', 'Superb'],
}
